translations/OpenOrienteering_sv.ts

Before merging this has to be tested(help wanted).
[Testing Translations](https://github.com/OpenOrienteering/mapper/wiki/Translation)

Updated Swedish translations

---

translations/OpenOrienteering_sv.ts

Some conflicts that needs to be solved(or fixed by regenerate translation?).

About 460 Translated Swedish Strings

---

translations/OpenOrienteering_sv.ts

Adding translations for new values and updating some of the existing ones based on feedback/usage.

Update Swedish translations

---

translations/CMakeLists.txt
translations/OpenOrienteering_ru.ts

Added Russian translation file. It had been tested in 0.6.0 release.

Russian translate

---

translations/OpenOrienteering_uk.ts

(772 finished and 462 unfinished items)

Ukrainian translation - small fixes and improvements

---

translations/OpenOrienteering_nb.ts

Hi!
I had a quick proofreading of the Norwegian translation. Overall very good, but I fixed some smaller things. Also, I had a look at the things marked as unfinished.
Cheers,
Kjetil

Some proofreading of nb translation

---

translations/OpenOrienteering_sv.ts

Based on discussion in #587 and cherry picked from there.
Some discussions should be occurring before merge.

Cherry pick from #587

---

packaging/debian/openorienteering-mapper.xml

Added Ukrainian comment for map MIME type

---

src/symbol_text.cpp
src/symbol_text.h

TextSymbolSettings: Redesign font/letter size

---

src/gui/print_widget.cpp

If `dpi` sufix in popup list translated impossible to change the print resolution.

Fixed print resolution validator

---

src/gdal/mapper-osmconf.ini
symbol sets/OSM-ISOM2000.crt

OSM import with GDAL (+CRT)

---

src/tools/draw_path_tool.cpp
src/tools/draw_path_tool.h
src/tools/tool_helpers.cpp
src/tools/tool_helpers.h

The feature can be activated by pressing Ctrl-Space or "Info" button in mobile UI.
References: Issue #398

Show line segment length and azimuth while drawing

---

src/core/map.cpp
src/core/map.h
src/gui/main_window.cpp
src/gui/main_window.h
src/gui/main_window_controller.cpp
src/gui/main_window_controller.h
src/gui/map/map_editor.cpp
src/gui/map/map_editor.h

This PR adds missing pieces, cleans up the API, and applies to ocd-export.

Respect user-selected file format when saving

---

translations/OpenOrienteering_cs.ts

This reverts commit 8826f7faf809d4db1121e094753a139955a5d65e.

Revert some translations (Čeština)

---

src/core/map_color.cpp
src/core/map_color.h
src/fileformats/ocd_file_export.cpp
src/fileformats/ocd_file_import.cpp
src/fileformats/ocd_types_v8.h
src/fileformats/xml_file_format.cpp
src/fileformats/xml_file_format.h
src/gui/color_dialog.cpp
src/gui/color_dialog.h
src/gui/widgets/color_list_widget.cpp
test/map_color_t.cpp

I will merge this without waiting for approval, but for review and commenting, an explicit PR still seems beneficial.

Spot color properties

---

code-check-wrapper.sh
src/gui/map/map_editor.cpp
src/sensors/gps_display.cpp
src/sensors/gps_display.h

GPS location highlighting

---

src/tools/draw_path_tool.cpp

I'm not completely sure I understood the code in draw path tool right but made my best to test all cases which came to my mind. Please review with extra care.

DrawPathTool: Fix corner point handling

---

code-check-wrapper.sh
src/fileformats/ocd_types.cpp
src/fileformats/ocd_types.h
test/CMakeLists.txt
test/file_format_t.cpp
test/file_format_t.h
test/ocd_t.cpp

Ocd: Review and test string assignments

---

src/gui/widgets/symbol_render_widget.cpp

When deleting multiple symbols, users may be asked very often to
confirm deleting the affected objects. This changes adds "Yes to all"
and "Cancel" options which will both cause the dialog to not appear
again for the current operation.
For "Cancel" to affect the whole operation, the confirmation request
is moved to the first sub-step where the symbols are collected for
later deletion.
Resolves GH-1200.

Add YesToAll and Cancel to symbol deletion

---

src/gui/georeferencing_dialog.cpp
src/gui/map/map_dialog_rotate.cpp
src/gui/map/map_dialog_scale.cpp
src/gui/map/map_dialog_scale.h

First changes from #1268 (the remainder needing more thought), plus a fix for syntactic warning.

Map dialogs, part a

---

ci/azure-pipelines.yml

CI: Enable Android x86 and 64 bits builds

---

translations/OpenOrienteering_cs.ts
translations/OpenOrienteering_da.ts
translations/OpenOrienteering_de.ts
translations/OpenOrienteering_eo.ts
translations/OpenOrienteering_es.ts
translations/OpenOrienteering_et.ts
translations/OpenOrienteering_eu.ts
translations/OpenOrienteering_fi.ts
translations/OpenOrienteering_fr.ts
translations/OpenOrienteering_he.ts
translations/OpenOrienteering_hr.ts
translations/OpenOrienteering_hu.ts
translations/OpenOrienteering_id.ts
translations/OpenOrienteering_it.ts
translations/OpenOrienteering_ja.ts
translations/OpenOrienteering_lv.ts
translations/OpenOrienteering_nb.ts
translations/OpenOrienteering_nl.ts
translations/OpenOrienteering_pl.ts
translations/OpenOrienteering_pt_BR.ts
translations/OpenOrienteering_pt_PT.ts
translations/OpenOrienteering_ru.ts
translations/OpenOrienteering_sv.ts
translations/OpenOrienteering_template.ts
translations/OpenOrienteering_uk.ts
translations/OpenOrienteering_zh_CN.ts

Beside general changes, this reestablishes the Latvian translations
as not 'vanished'.

translations: Update from source

---

src/gui/print_widget.h

Fix for a buglet in the include guard.

PrintWidget: Fix wrong #endif placement

---

src/tools/cut_tool.cpp

CutTool: Fix line cutting operations

---

src/gui/widgets/editor_settings_page.cpp
src/gui/widgets/editor_settings_page.h

EditorSettingsPage: Fix non-mobile mode

---

src/gui/map/map_editor.h

MapEditorController: Restore importClicked() slot

---

code-check-wrapper.sh
src/CMakeLists.txt
src/android/java/org/openorienteering/mapper/MapperActivity.java
src/gui/main_window.cpp
src/gui/main_window.h
src/gui/widgets/symbol_tooltip.cpp
src/gui/widgets/symbol_tooltip.h
src/gui/widgets/toast.cpp
src/gui/widgets/toast.h

Fix GH-1305 by own implementation.

Replace Android system Toast

---

ci/build.yml
src/gui/main_window.cpp
src/gui/main_window.h
src/gui/print_progress_dialog.cpp
src/gui/widgets/home_screen_widget.cpp
src/gui/widgets/template_list_widget.cpp
src/gui/widgets/toast.h

Minor corrections

---

code-check-wrapper.sh
iwyu-mapper.imp
src/CMakeLists.txt
src/gdal/CMakeLists.txt
src/gdal/gdal_template.cpp
src/gdal/gdal_template.h
src/gui/print_widget.cpp
src/templates/template_image.cpp
src/templates/template_image.h
src/templates/template_image_open_dialog.cpp
src/templates/template_image_open_dialog.h
src/templates/world_file.cpp
test/template_t.cpp

Use GDAL raster support at least for finding georeferencing information. This could handle more than GeoTIFF, but only the latter was tested

Basic GeoTIFF support

---

src/core/map_coord.h
src/core/path_coord.h
src/core/virtual_path.cpp
test/path_object_t.cpp
test/path_object_t.h

The issue with losing dash points at start or end of a path (GH-1323) had a root deep in path copying. This fix has the potential for unexpected side effects. However, it comes with more test coverage.

Fix path copying/cutting issues

---

src/gui/about_dialog.cpp

Who else is missing explicit mention?

Update lists of developers and contributors

---

ci/openorienteering-mapper-ci.cmake
src/core/objects/object.cpp
src/core/objects/object.h
src/tools/cut_tool.cpp
test/path_object_t.cpp
test/path_object_t.h

Trying to get down the number of flagged lines in Qt Creator...

Revise Object classes, part 1

---

src/core/objects/object_mover.cpp
src/core/objects/object_mover.h
src/tools/edit_line_tool.cpp
src/tools/edit_point_tool.cpp
src/util/util.cpp
src/util/util.h
test/util_t.cpp

Implementation of GH-1345 enhancement.

Corner point "click in" editing mode

---

src/gdal/gdal_template.cpp
src/templates/template_image.cpp

Improve handling of georeferenced templates

---

src/CMakeLists.txt
src/gui/main_window.cpp
src/main.cpp

Clean various warnings displayed in Qt Creator editor.
Fix some quirks discovered during inspection.

Revise main.cpp

---

src/gdal/ogr_file_format.cpp
src/gdal/ogr_template.cpp
src/gdal/ogr_template.h
test/data/templates/map.osm
test/template_t.cpp

Fix OGR georeferencing setup

---

ci/build.yml
ci/openorienteering-mapper-ci.cmake

Eliminate second git clone by direct access to the existing checkout.

CI: Simplify cmake script for superbuild

---

src/fileformats/ocd_file_export.cpp
src/fileformats/ocd_file_import.cpp

OcdFileExport/Import: Handle V12 area clipping

---

ci/azure-pipelines.yml
ci/publish-coverage.yml

Amends 71a0278e. Fixes missing coverage info on Azure Pipelines.

CI: Fix gcovr invocation

---

src/gdal/ogr_file_format.cpp
test/file_format_t.cpp
test/file_format_t.h

Task: GH-1433 (swapped latitude/longitude)

FileFormatTest: Cover OGR georeferencing export/import

---

symbol sets/10000/ISSkiOM 2019_10000.omap
symbol sets/12500/ISSkiOM 2019_12500.omap
symbol sets/5000/ISSkiOM 2019_5000.omap
symbol sets/7500/ISSkiOM 2019_7500.omap
test/symbol_set_t.cpp

Fixes GH-1441 (unexpected scaling dialog for new SkiO map).

ISSkiOM 2019: Fix scaled variants

---

src/templates/template.cpp

Fixes GH-742 (list of pass points not duplicated).

Template: Copy pass points

---

src/undo/object_undo.cpp

SwitchSymbolUndoStep: Fix build with Qt 5.9

---

src/fileformats/ocd_file_export.cpp

Amends ec41f6db, Task: GH-1452 (emtpy map display in Condes).

OcdFileExport: Fix per-symbol color list

---

src/util/transformation.h
test/georeferencing_t.cpp
test/georeferencing_t.h

The trivial part from GH-1277.

Georeferencing cleanup

---

3rd-party/cove/libvectorizer/Concurrency.h
3rd-party/cove/libvectorizer/ParallelImageProcessing.cpp
3rd-party/cove/libvectorizer/ParallelImageProcessing.h
3rd-party/cove/libvectorizer/Vectorizer.cpp
3rd-party/cove/tests/CMakeLists.txt
3rd-party/cove/tests/ParallelImageProcessingTest.cpp
3rd-party/cove/tests/PolygonTest.cpp

Assumed to (help) resolve GH-1503.
However, not yet tested in an environment which reproduces the issue.

Fix concurrent image processing

---

src/tools/draw_path_tool.cpp
src/tools/tool_helpers.h

Cosmetic tool changes

---

src/core/objects/object.cpp
src/core/objects/object.h
src/core/symbols/line_symbol.cpp
src/core/symbols/line_symbol.h
src/tools/draw_path_tool.cpp
src/tools/tool_helpers.cpp
src/tools/tool_helpers.h

Resolves GH-273 (follow a path's outline).

DrawPathTool: Follow border lines

---

src/core/objects/object.cpp
src/core/objects/object.h
src/core/symbols/combined_symbol.cpp
src/core/symbols/combined_symbol.h
src/core/symbols/line_symbol.cpp
src/core/symbols/line_symbol.h
src/core/symbols/symbol.cpp
src/core/symbols/symbol.h
src/tools/draw_path_tool.cpp
src/tools/tool_helpers.cpp
src/tools/tool_helpers.h

Improve quality.
Support combined symbols (e.g. Road with two carriageways).
Task: GH-273

Elaborate follow-border feature

---

src/gdal/ogr_file_format.cpp
test/CMakeLists.txt
test/georeferencing_t.cpp

Task: GH-1570 (GPX misalignment)

GeoreferencingTest: Add EPSG 27700 (OSGB36) point

---

src/core/objects/object.cpp
src/core/objects/object.h
src/core/path_coord.h
src/core/virtual_path.cpp
src/core/virtual_path.h
src/tools/cut_tool.cpp
src/tools/draw_path_tool.cpp
src/tools/edit_line_tool.cpp
src/tools/edit_point_tool.cpp
src/tools/fill_tool.cpp
src/tools/tool_helpers.cpp

Follow-up to touching some functions for implementing the follow-border feature.

Revise result handling, types, and various warnings in core, tools

---

src/gui/map/map_editor.cpp

MapEditorController: Add template list tool button

---

src/gdal/mapper-osmconf.ini
symbol sets/OSM-ISOM 2017-2.crt
symbol sets/OSM-ISSkiOM 2019.crt
symbol sets/OSM-ISSprOM 2019.crt

mapper-osmconf.ini: Fix area and bridge

---

src/fileformats/ocd_file_export.cpp
src/fileformats/ocd_file_export.h
src/fileformats/ocd_file_import.cpp

There are some todos left in the last commit, but this part seems to be ready for review/testing.

OCD support improvements

---

src/core/map.cpp
src/core/map.h
src/core/map_view.cpp
src/core/map_view.h
src/fileformats/file_import_export.cpp
src/gui/map/map_editor.cpp
src/gui/map/map_widget.cpp
src/gui/map/map_widget.h
src/gui/widgets/template_list_widget.cpp
src/gui/widgets/template_list_widget.h
src/templates/template_map.cpp
src/templates/template_table_model.cpp
src/templates/template_table_model.h
test/data/templates/ogr-template.xmap
test/data/templates/template-track.xmap
test/template_t.cpp

Simplify by reassigning reponsibilities. Prepare for more concurrency.

Template loading refactoring

---

3rd-party/cove/app/colorseditform.cpp
3rd-party/cove/app/mainform.cpp
3rd-party/cove/app/mainform.h
src/core/map_coord.h
src/gui/autosave_dialog.h
src/gui/color_dialog.h
src/gui/georeferencing_dialog.cpp
src/gui/map/map_editor.cpp
src/gui/map/new_map_dialog.cpp
src/gui/print_progress_dialog.h
src/gui/symbols/area_symbol_settings.cpp
src/gui/symbols/symbol_replacement_dialog.cpp
src/gui/widgets/measure_widget.cpp
src/gui/widgets/symbol_dropdown.cpp
src/templates/paint_on_template_feature.cpp
src/templates/template_track.cpp
src/tools/draw_point_tool.cpp
src/tools/rotate_pattern_tool.cpp
src/tools/rotate_tool.cpp
src/tools/tool_helpers.cpp
test/tools_t.cpp

Address deprecation warnings reported by GCC 10 compiler with Qt 5.15 on openSUSE Tumbleweed.

Deprecated methods cleanup

---

src/fileformats/ocd_file_export.cpp
src/fileformats/ocd_file_import.cpp

Fixes for GH-1685. As they are changes to code written by you, Kai, I'd love to hear your opinion on them. Thanks!
The fix for division by zero should definitely go into v0.9.4 as it is a regression.

Fix area import and export

---

src/gui/map/map_find_feature.cpp

Resolves GH-1683 (orphan window).

MapFindFeature: Tear down the dialog on destruction

---

src/gui/map/map_editor.cpp
src/gui/map/map_editor.h
src/gui/map/map_editor_activity.h
src/gui/widgets/template_list_widget.cpp
src/templates/template_adjust.cpp
src/templates/template_adjust.h

Simplify, and fix lifecycle. Includes fix for GH-1690 (crash when closing template adjustment dock widget on macOS).

Revise editor activity handling

---

src/gui/print_widget.cpp

Resolves GH-1271 (resolution selection difficulties).

PrintWidget: Use default resolution for image export

---

code-check-wrapper.sh
src/gui/map/map_editor.cpp
src/gui/widgets/mapper_proxystyle.cpp
src/gui/widgets/mapper_proxystyle.h
src/main.cpp

Proxy style updates for touch UI

---

src/gui/map/map_editor.cpp

MapEditorController: Avoid QMenu::aboutToShow

---

src/core/map_part.cpp
src/core/map_part.h
src/tools/draw_path_tool.cpp

Resolves GH-1708 (crash after appending to object in another part).

DrawPathTool: Limit appending to same part

---

src/gui/widgets/mapper_proxystyle.cpp
src/gui/widgets/mapper_proxystyle.h

Improve touch mode spinbox buttons, for easier settings.
Move QCommonStyle casts out of hot paths.

Proxy style changes

---

src/templates/paint_on_template_tool.cpp
src/templates/paint_on_template_tool.h
src/templates/template.h
src/templates/template_image.cpp

Paint-on-template changes

---

3rd-party/cove/app/colorseditform.cpp
3rd-party/cove/app/mainform.cpp
3rd-party/cove/app/mainform.h
src/core/map_coord.h
src/gui/autosave_dialog.h
src/gui/color_dialog.h
src/gui/georeferencing_dialog.cpp
src/gui/map/map_editor.cpp
src/gui/map/new_map_dialog.cpp
src/gui/print_progress_dialog.h
src/gui/symbols/area_symbol_settings.cpp
src/gui/symbols/symbol_replacement_dialog.cpp
src/gui/widgets/measure_widget.cpp
src/gui/widgets/symbol_dropdown.cpp
src/templates/template_track.cpp
src/tools/draw_point_tool.cpp
src/tools/rotate_pattern_tool.cpp
src/tools/rotate_tool.cpp
src/tools/tool_helpers.cpp
test/tools_t.cpp

Patch set from PR 1681 rebased to current master.

Deprecated methods cleanup (for master)

---

test/file_format_t.cpp

gcc 6 fails to bind a const object to a named reference in the
capture list of a lambda.

FileFormatTest: Fix FTBFS with Debian 9

---

test/data/templates/template-track-NA-084.xmap
test/data/templates/template-track-NA-093-GDAL.xmap
test/data/templates/template-track-NA-093-PROJ.xmap
test/data/templates/template-track-NA-2019.gpx
test/data/templates/template-track-NA.xmap
test/template_t.cpp

Closes GH-1764 (pristine version of this PR).
@pkturner I can add you as a GH project member ("Registered Contributor" group) to acknowledge your input and to allow to add you formally as a reviewer to PRs.

Test NAD83 GPX templates

---

3rd-party/cove/libvectorizer/Concurrency.h
src/gdal/ogr_file_format.cpp

Fix compiler warnings

---

test/data/templates/template-track-NA-2019.gpx

A tiny PR, which @dg0yt hinted at in discussion of GH #1771.
Added comment describing the peculiar relationship between the track and the map it fits with.

Add descriptive comment to track in templateTrackTest

---

src/gdal/kmz_groundoverlay_export.cpp
src/gdal/kmz_groundoverlay_export.h
src/gui/print_widget.cpp
src/gui/print_widget.h

...including single-image option.
Task: GH-1883 (Vikazimut compatibility)

Add tile size configuration to KMZ export

---

src/gui/widgets/paint_on_template_settings_page.cpp

Field-tested color sets contributed by Martin Lerjen and Aleš Hejna.
Code-wise the change is trivial, and I'll merge it as soon as tests complete.

PaintOnTemplateSettingsPage: Update presets

---

src/gui/print_widget.cpp

Check return value of MapPrinter::kmzTarget() against selected target.

---

ci/codespell.yml
codespell-ignore.txt
codespell.sh

To resolve corner cases, use a list of accepted lines.

Update codespell scripts

---

src/gui/scaling_icon_engine.cpp

QIconEngine::actualSize() is documented to return the requested size
by default, but the actual implementations behave differently. In
particular, they seem to preserve the aspect ratio of the source,
fitting the actual size into the requested size. This commit changes
our icon engine to follow this pattern.
Fixes GH-1928 (Unreadable font names due to excessive font icon size).

ScalingIconEngine: Keep aspect ratio

---

src/core/map_coord.cpp
test/file_format_t.cpp
test/file_format_t.h

Fix OMAP reading problems from SMTP transfer

---

src/fileformats/ocd_georef_fields.cpp

This commit adds the OCD IDs 20016-20023 and their mapping to EPSG 7489-7856.
Closes #1976

OCD: Add OcdGrid::Australia zones GDA2020/MGA zone 49-56

---

src/templates/template.cpp

Mapper always saves and loads the alternative template transformation. But in some cases, files seem to have transforms with coordinates which were not update properly when moving the map into the regular  domain. Instead of not loading these files at all, catch the exception silently.
There is no evidence that this exception would also occur for the active transform, so error handling for this data remains unchanged for now.
Task: GH-1969

Template: Catch some coordinate exceptions

---

test/template_t.cpp

TemplateTest: Update expected fails for PROJ 8.2.0

---

symbol sets/README.md

Subset from #2042 by @mlerjen.

Update symbol sets README

---

src/core/map.cpp
src/core/map.h
src/fileformats/ocd_file_export.cpp
src/fileformats/ocd_icon.cpp

Random fixes that were made during the analysis and fixing of #2012. Take them or leave them.

Random fixes in .ocd export

---

test/georeferencing_t.cpp
test/georeferencing_t.h

Test the determination of the UTM zone from the given latitude and longitude, especially for the exceptions in the Southwest of Norway and in the region around Svalbard.

GeoreferencingTest: Test UTM zone calculation

---

3rd-party/cove/tests/CMakeLists.txt
CMakeLists.txt
packaging/android/CMakeLists.txt

Fix CMake configuration warnings

---

ci/azure-pipelines.yml
ci/setup-macos.yml

ci: Switch to macos-12 image

---

3rd-party/cove/libvectorizer/Polygons.cpp
3rd-party/cove/tests/CMakeLists.txt

cove: Minor improvements

---

ci/setup-macos.yml

ci: Update Android SDK setup

---

CMakeLists.txt
ci/azure-pipelines.yml
ci/setup-common.yml
ci/setup-macos.yml

Control MACOSX_DEPLOYMENT_TARGET.

ci: Update for runner image changes

---

src/gui/about_dialog.cpp

I'm not sure that I'll have enough time to substantially contribute to OO Mapper in the future. Please review the "activity years" for correctness. Thanks!

AboutDialog: Update the developer list

---

src/tools/object_selector.cpp
src/tools/object_selector.h

Fix TODO for sortObjects() by embedding into the new function sortObjectSelection().

ObjectSelector: Refactoring

---

src/gui/symbols/point_symbol_editor_widget.cpp

Fix an obvious copy&paste error (duplicate usage of point_outer_width_edit instead of point_outer_color_edit).
Use QSignalBlocker and ScopedMultiSignalsBlocker classes to block signals.

PointSymbolEditorWidget: Fix and refactor signal blocking

---

packaging/CMakeLists.txt
packaging/macos/hdiutil.sh

Mitigate interference from XProtect.

Packaging: Retry 'hdiutil create'

---

ci/setup-msys2.yml

Prefer CI speed over proper CI warnings in AZP.

CI: Simplify wrapping for msys2

---

src/tools/draw_path_tool.cpp

DrawPathTool: Fix crash

---

ci/azure-pipelines.yml
ci/setup-ubuntu.yml

Closes GH-2329 (Update Ubuntu Actions runner image).

CI: Update Ubuntu Actions runner image

---

src/core/map.cpp
src/core/map.h
src/fileformats/xml_file_format.cpp
src/templates/template_image_open_dialog.cpp

Refactoring image template default parameters

---

src/gui/georeferencing_dialog.cpp

Since NCEI's Magnetic Field Calculator requests an access key change to the online declination calculator of the British Geological Survey (BGS).
Closes GH-2087 (Magnetic declination lookup button does not work).
Supersedes GH-2088, GH-2255.

GeoreferencingDialog: Replace online declination calculator

---

src/core/objects/object.cpp
src/core/objects/object.h
src/gui/widgets/measure_widget.cpp
test/object_t.cpp

Fix typo in function name

---

translations/OpenOrienteering_fi.ts

Currently translated at 100.0% (1535 of 1535 strings)

Translated using Weblate (Finnish)
