translations/OpenOrienteering_sv.ts
This was caused by the earlier update to the translations but first discovered now.
=> Fix broken Swedish translation for zoom factor

translations/OpenOrienteering_sv.ts
Last time I updated the vanished instance of the string... :imp:
=> Minor fix to Swedish translation

src/util.cpp
The problem is that I couldn't open the manual (just nothing happened, no error messages).
After looking at `strace ./Mapper` output, I discovered the follow error:
`assistant: could not find a Qt installation of 'qt5'`
Ther reason is that on ArchLinux/LFS:
```
> qtchooser -list-versions
4
5
default
```
But #541 works for Debian/Ubuntu, where both qt5 and 5 exist.
=> Set QT_SELECT=5 instead of QT_SELECT=qt5 env variable for Assistant

packaging/CMakeLists.txt, packaging/debian/Mapper.desktop, packaging/debian/openorienteering-mapper.xml
Added MIME types:
- application/x-openorienteering-omap for *.omap files;
- application/x-openorienteering-xmap for *.xmap files.
Associated these MIME types with OOMapper.
Tested in Xununtu 14.04 with Thunar and Nautilus.
Issue #756
=> Added MIME types of *.omap and *.xmap files

translations/OpenOrienteering_id.ts
This is small fixes that correcting various inconsistent capitalization usage in Indonesian translation. For rule of thumbs, capitalization usage in Bahasa Indonesia is similiar with English.
Example:
```xml
<source>Show tip of the day</source>
<translation>Tampilkan Tips</translation>
```
became
```xml
<source>Show tip of the day</source>
<translation>Tampilkan tips</translation>
```
Mention to @arifbobidinamik, the original Bahasa Indonesia translator.
=> Fix inconsistent caps usage in Indonesian translation

src/gui/symbols/replace_symbol_set_dialog.cpp
Currently the code won't match up symbols correctly if the target symbol has a minor number due to a typo.
=> Fix CRT symbol mapping when symbol has a minor number

src/core/symbols/area_symbol.cpp, src/core/symbols/area_symbol.h, src/core/symbols/point_symbol.cpp, src/core/symbols/point_symbol.h, src/fileformats/ocad8_file_format.cpp, src/fileformats/ocd_file_import.cpp, src/gui/symbols/area_symbol_settings.cpp, src/gui/symbols/area_symbol_settings.h, src/gui/symbols/symbol_setting_dialog.cpp
Alternatives added in last commit (272e0b3).
Includes cleanup and modernization of this AreaSymbol and AreaSymbol::FillPattern.
=> Area symbol: Prepare alternatives to pattern clipping

src/CMakeLists.txt, src/core/map.cpp, src/core/map.h, src/core/objects/object_query.cpp, src/core/objects/object_query.h, src/core/objects/symbol_rule_set.cpp, src/core/objects/symbol_rule_set.h, src/gui/map/map_editor.cpp, src/gui/map/map_editor.h, src/gui/symbols/replace_symbol_set_dialog.cpp, src/gui/symbols/replace_symbol_set_dialog.h, symbol sets/OSM-ISOM2000.crt, test/map_t.cpp, test/map_t.h, test/object_query_t.cpp, test/object_query_t.h
Until now, CRT file support was limited to DXF import. These changes leverage ObjectQuery for powerful symbol replacement and CRT file support:
- CRT files may be loaded during symbol set replacement operations.
- CRT files may be loaded at any time, searching for symbol numbers or any tag contents. In the future, there could be complex queries, e.g. for complex OSM tag combinations.
- Symbol replacement/assignments may be saved to CRT files.
=> Elaborate and leverage ObjectQuery and CRT file support

src/fileformats/ocad8_file_format.cpp, src/fileformats/ocad8_file_format_p.h
Do not just issue a warning, but move coordinates as needed to make objects visible in the bounds of the OCAD drawing area.
=> OCAD8FileExport: Move coords into OCAD 8 drawing area

CMakeLists.txt, android/AndroidManifest.xml
Since 0.7.0, there has been a lot of new features:
- modified pattern clipping (change in file format)
- ISOM 2017 symbol set
- symbol set translations
- Find dialog with object queries
- advanced CRT file support with object queries
- CRT files for ISOM2017 and OSM
- modified dash symbol scaling (change in file format)
plus a lot of refactoring and fixes. Cf. https://github.com/OpenOrienteering/mapper/issues?utf8=%E2%9C%93&q=milestone%3Av0.7.1%20. (Documentation is lagging as usual...)
So I would suggest to use 0.8.0, and to repeat the deprecation warnings (file formats, OS X 10.7) rather than activating these changes.
=> Set version to 0.8.0

src/core/objects/object.cpp, src/core/symbols/area_symbol.cpp, src/core/symbols/line_symbol.cpp, src/sensors/gps_track.cpp, src/tools/draw_rectangle_tool.cpp, src/util/matrix.h
Changelog:
- replace '(ptr1 && !ptr2) || (!ptr1 && ptr2)' with 'bool(ptr1) != bool(ptr2)'
- replace '!A || (A && B)' with '!A || B'
- protect copy operators against self-assignment
=> Simplify logic expressions

translations/qt_eo.ts, translations/qt_et.ts, translations/qt_id.ts, translations/qt_lv.ts, translations/qt_nb.ts, translations/qt_nl.ts, translations/qt_template.ts
Changelog:
- Added some more missing qt messages (https://github.com/OpenOrienteering/mapper/pull/926#issuecomment-324529483)
- Updated to use `&quot;` and `&apos;`
=> Add missing Qt messages

translations/OpenOrienteering_cs.ts, translations/OpenOrienteering_de.ts, translations/OpenOrienteering_es.ts, translations/OpenOrienteering_fi.ts, translations/OpenOrienteering_fr.ts, translations/OpenOrienteering_hu.ts, translations/OpenOrienteering_it.ts, translations/OpenOrienteering_ja.ts, translations/OpenOrienteering_lv.ts, translations/OpenOrienteering_nb.ts, translations/OpenOrienteering_nl.ts, translations/OpenOrienteering_pl.ts, translations/OpenOrienteering_pt_BR.ts, translations/OpenOrienteering_ru.ts, translations/OpenOrienteering_sv.ts, translations/locversion.plist.in, translations/qt_eo.ts, translations/qt_et.ts, translations/qt_id.ts, translations/qt_lv.ts, translations/qt_nb.ts, translations/qt_nl.ts, translations/qt_template.ts
Briefly:
- (es,fr,hu,ja,pl,pt_BR,sv,de,ru,cs,it,fi) Removed MAC_APPLICATION_MENU context from OpenOrienteering_\*.ts
- (lv,nb,nl) Moved MAC_APPLICATION_MENU context from OpenOrienteering_\*.ts to qt_\*.ts
- (qt_template.ts) Added MAC_APPLICATION_MENU context
- (locversion.plist.in) Fixed s/@LANGUAGE_CODE@/@language_code@/ (https://github.com/OpenOrienteering/mapper/commit/38a3ed259b5d39be96ea7b27f3732c797aac6ed2, v0.7.91 is affected)
MAC_APPLICATION_MENU was initially introduced in https://github.com/OpenOrienteering/mapper/commit/8781511136d06bf40b1d8ffb864322a928e780a8 due to lack of translations in Qt 5.0.1, and removed in https://github.com/OpenOrienteering/mapper/commit/59ef03784b67967f0a2900d0fe3573415405ebb6.
Status of MAC_APPLICATION_MENU translation in Qt:
| locale | Qt |
| …
=> Fix OSX application menu

translations/OpenOrienteering_cs.ts, translations/OpenOrienteering_de.ts, translations/OpenOrienteering_eo.ts, translations/OpenOrienteering_es.ts, translations/OpenOrienteering_fi.ts, translations/OpenOrienteering_fr.ts, translations/OpenOrienteering_hu.ts, translations/OpenOrienteering_id.ts, translations/OpenOrienteering_it.ts, translations/OpenOrienteering_ja.ts, translations/OpenOrienteering_lv.ts, translations/OpenOrienteering_nb.ts, translations/OpenOrienteering_nl.ts, translations/OpenOrienteering_pl.ts, translations/OpenOrienteering_pt_BR.ts, translations/OpenOrienteering_ru.ts, translations/OpenOrienteering_sv.ts, translations/OpenOrienteering_uk.ts
The malformed translation propagates onto screen and leaks out of its text rectangle. ![image](https://user-images.githubusercontent.com/5584406/32514982-e05fa1cc-c3fe-11e7-8e26-d6d4c4f44f93.png)
=> translations: quick-fix azimuth helper text

INSTALL.md
A space separated list is easier to copy-paste into a terminal, whereas the comma separated list would not run (for example with `sudo apt install cmake, ...`
=> Change package list to space separated and mark as code block

src/sensors/gps_track.cpp, src/sensors/gps_track_recorder.cpp
While trying to merge GPX files from Mapper and another source, I noticed that Mapper records times in local time zone.
=> Fix GPX record time stamp

test/transform_t.cpp
This is the minimal change to skip tests failing with Qt 5.11.1. Use of QEXPECT_FAIL would require modification at four places or definition of a new inline function. Given the importance of this issue I opted for minimal code footprint.
=> transform_t: Avoid hitting a Qt bug

src/core/map.cpp, src/core/storage_location.cpp, src/core/storage_location.h
This is an attempt to resolve #1115.
In several cases, the files had correct but incomplete data, and/or transfers after an Android reboot were complete. This reboot effect was observed before for README files put into the data folders, and solved by Android::mediaScannerScanFile(). So there is a chance that using the same pattern might eventually resolve #1115, by forcing the media scanner to take immediate notice of the changed file.
(Note that we use QSaveFile which does actually not update the existing file but replace it with a new file by renaming.)
=> Android: Trigger MediaScanner after saving

src/core/storage_location.cpp, src/core/storage_location.h, src/gui/widgets/home_screen_widget.cpp, src/gui/widgets/home_screen_widget.h
With this change, the mobile UI no longer show a single list of all maps in known locations, but:
1. Lists most recently used maps first (as on desktop).
2. If there are no such maps, show a link to the manual page.
3. List the known storage locations (unique full path).
4. Show a link to the examples folder.
When clicking on a folder, the folder contents will be displayed as follows:
1. Show ".." entry which navigates back.
2. List map files in this directory.
3. List subdirectories.
This change does not allow browsing to other locations.
Geospatial vector files will no longer be listed when they are handled by GDAL/OGR.
The "File list" headline and the redundant "Examples" button are removed.
This change at resolves or at least mitigates #904. However, this change does not add custom …
=> Android: Show recent files, browse folders

src/core/renderables/renderable.h, src/templates/template_map.cpp
When drawing the map, RenderConfig::scaling must be set to the number
of pixels per mm. Fixes #1186.
=> TemplateMap: Fix RenderConfig::scaling

src/core/map.cpp, src/core/map.h, src/core/map_grid.cpp, src/core/map_grid.h, src/core/map_printer.cpp, src/core/map_printer.h, src/core/map_view.cpp, src/core/map_view.h, src/gui/map/map_widget.cpp, src/gui/print_widget.cpp, src/templates/template.cpp, src/templates/template.h, src/templates/template_image.cpp, src/templates/template_map.cpp, src/templates/template_map.h, src/templates/template_track.cpp, src/templates/template_track.h, test/map_t.cpp, test/map_t.h
This is a series of patches make the core MapPrinter::drawPage() function much easier to understand. It is a significant modification to the `master` branch, but I don't see a simpler way to eventually fix #1163.
There is still room for improvement, now more obvious than before, and more easy to add on top:
- Reduced opacity of the map "layer" will still trigger rasterization even when vector mode is selected - i.e. we must enforce 100% opacity for vector mode.
- In a similar way, rasterization might possibly be triggered from vector templates which are not 100% opaque. We might handle them like raster templates and rasterize them in the background, or we may handle them like the map "layer" and draw them 100% opaque in the foreground.
- I still need to verify if non-opaque colors in a …
=> Review printing

src/undo/object_undo.cpp, src/undo/object_undo.h
The first commit is just a modernization. The second one fixes a clazy warning which pointed to a DRY violation. This should result in one compiler warning disappearing in the new CI, so that's why I'm inviting more reviewers than usual.
=> Rewrite object tags undo save/load

src/core/map.cpp
Alteration of protected objects comes as a surprise to users.
=> Map: Prevent selecting hidden and protected symbols

test/georeferencing_t.cpp, test/georeferencing_t.h
pj_set_finder() is deprecated API since PROJ 6.0.0. Cf. GH-1214.
=> GeoreferencingTest: Check PROJ's pj_set_finder()

src/gui/widgets/symbol_render_widget.cpp
When deleting more than half of the symbols at one go (and the second one that is clicked on is after the first one), and then creating a new symbol; Mapper crashes.
This crash is due to the fact that current_symbol_index is still at the index of the last symbol clicked on and is now out of bounds so AddSymbol crashes when trying to add a new symbol there.
Solve it by explicitly setting the selected symbol (and therefore current_symbol_index) to the invalid -1
=> SymbolRenderWidget: Fix crash when deleting multiple symbols

src/gui/map/map_editor.cpp, src/templates/template_tool_paint.cpp, src/tools/tool.h
Usability defect pointed out by mlerjen in issue #1143. I chose `Scribble` name as it's an established name for the tool among its users and `PaintOnTemplate` feels clumsy.
=> Allow tool switch when selecting symbol in scribble mode

CMakeLists.txt, src/gui/util_gui.cpp, src/gui/util_gui.h, src/tools/rotate_tool.cpp, src/tools/scale_tool.cpp, src/tools/scale_tool.h
This is continuation of PR#1203 which got closed inadvertently.
This pull request adds a new operation mode to Scale tool. When holding `Ctrl` key, the resize operation uses object center (center of the enclosing rectangle) as the origin. Further patches in the series refine the code change in sense of code deduplication and TODO removal.
`Ctrl` + drag to resize multiple objects:
=> Scale tool enhancement

code-check-wrapper.sh, src/core/crs_template_implementation.cpp, src/core/crs_template_implementation.h, src/gui/georeferencing_dialog.cpp, src/gui/widgets/crs_param_widgets.cpp, src/gui/widgets/crs_param_widgets.h
Most fields in the Georeferencing dialog were hard to edit because the cursor jumped to the end of the text after each key press. This is fixed by not touching the field if we don't have a new value.
=> Fix editing of Georeferencing fields

src/templates/template.cpp
TemplateTransform::operator== compares all the other members, but missed comparing the template_y member. Simple fix.
=> Compare TemplateTransforms will check template_y member

src/gui/widgets/template_list_widget.cpp
When importing a template map, objects need their coordinates transformed in the steps: scale, rotate, translate. This order needs to be the opposite of how they are applied to QPainter for drawing templates.
To experience the bug,
1. Open a map and add a template map.
1. Use the template dialog's positioning widget to set obvious rotation and non-isotropic scaling, such as rotation of 90, scale-x of 2, and scale-y of 0.5.
1. Observe that the template map is rotated counter-clockwise, and is greatly elongated vertically.
1. Use the template dialog's feature to import and remove the template map.
1. Observe that the imported map is now greatly elongated horizontally.
The imported features should not have changed their location/scaling. The rotation and scaling were applied correctly to the …
=> Fix transform used when importing a template map

android/AndroidManifest.xml, android/src/org/openorienteering/mapper/MapperActivity.java, android/src/org/openorienteering/mapper/MapperService.java, src/CMakeLists.txt, src/gui/main_window.cpp, src/gui/main_window.h, src/util/mapper_service_proxy.cpp, src/util/mapper_service_proxy.h
To protect unsaved map changes and to keep continuity of track
recording when the screen is off or the app is in the background,
let MainWindow start an Android foreground service when the it
is told that the map is modified.
This is expected to resolve #576. However this needs to be verified
in the field, across build and device configurations.
=> MainWindow: Start an Android foreground service

src/fileformats/ocd_file_import.cpp
Recently I received an OCAD 12 georeferenced map at scale 1:10000. After opening it in Mapper-dev I could not match the real world coordinates from Mapper to coordinates from other map services. The root cause was a failure to parse the georeferencing string. Mapper failed to parse "10000.000000" and silently filled in "15000" as map scale. This commit fixes the parsing part but not the silent breakage.
=> OCD: Fix string type 1039 (georeferencing) import

ci/openorienteering-mapper-ci.cmake
CMake's internal Clang compiler information modules now depends on
a CMAKE_CXX_COMPILER_FRONTEND_VARIANT variable which is meant to
be computed by CMake. But this doesn't work for (some) explicit
toolchain configurations.
=> CI: Fix Android build with CMake 3.15

src/core/map_grid.cpp, src/util/util.h, test/CMakeLists.txt, test/grid_t.cpp
When the Map Grid is enabled, a negative rotation leads to offsets being interpreted in the wrong direction.
To reproduce,
1. Configure the grid to be visible with an additional rotation of -20°, and a vertical offset of 30 meters.
1. The horizontal lines show up offset downwards, whereas a positive vertical offset should move the lines toward the top.
1. The snap-to-grid feature snaps to the _correct_ grid intersections, which do not match the visible horizontal lines.
Alternatively,
1. Set georeferencing such that grivation is negative, and the origin of projected coordinates is offset from the map origin.
1. Projected coordinates of the visible horizontal lines do not match multiples of the vertical spacing.
1. The snap-to-grid feature snaps to the _correct_ grid intersections, which …
=> MapGrid: Fix offset direction

code-check-wrapper.sh, src/gui/settings_dialog.cpp, src/main.cpp, src/sensors/CMakeLists.txt, src/sensors/compass.cpp, src/sensors/compass.h, src/sensors/gps_display.cpp, src/sensors/gps_temporary_markers.cpp, src/sensors/gps_temporary_markers.h, src/sensors/gps_track_recorder.cpp, src/sensors/gps_track_recorder.h, src/sensors/powershell_position_plugin.cpp, src/sensors/powershell_position_plugin.h, src/sensors/powershell_position_plugin.json, src/sensors/powershell_position_source.cpp, src/sensors/powershell_position_source.h, src/sensors/sensors_settings_page.cpp, src/sensors/sensors_settings_page.h, src/settings.cpp, src/settings.h
For now, the new settings page allows:
- selecting the location source, and
- selecting the serial port for the NMEA source.
This PR also wraps the PowershellPositionSource into a proper plugin, so that it does not need any special treatment, apart from registering the (static) plugin.
=> Add Sensor settings

src/core/georeferencing.cpp
This change is a result of properly reporting the first sub-issue of GH-1325 and contribution documentation updates to the PROJ project:
For reliable conversions, t shall be initialized to HUGE_VAL to allow for proper selection of time-dependent operations if one of the CRS is dynamic.
Cf. https://github.com/OSGeo/PROJ/pull/1603#discussion_r323656045
=> Georeferencing: Pass t=HUGE_VAL to proj_trans

src/gui/map/map_editor.cpp, src/gui/map/map_editor.h
When creating a new map with touch mode enabled, Mapper crashed due to uninitialized map part UI components. This is just a minimal fix for now, to minimize risk of side effects. In the end, the controller state and UI setup will need much more work.
=> MapEditorController: Basic fix for map parts UI

ci/azure-pipelines.yml, src/core/objects/object.cpp, test/path_object_t.cpp
We have got slow jobs (on Windows), so we don't benefit much from
full concurrency of the other jobs. OTOH we may have parallel builds
which could also benefit from vacant jobs.
=> CI: Limit parallel jobs

ci/azure-pipelines.yml
This job is obsolete now, thanks to the native builds. Don't block
other queued jobs.
=> CI: Disable the MinGW cross job

src/main.cpp
Qt 5.12 introduced a special left button handling for Android
which breaks our edit tools. This change disables the new Qt
feature for now. Resolves GH-1373 (self-snapping behaviour).
=> main: Globally set QT_QPA_NO_TEXT_HANDLES

src/fileformats/ocad8_file_format.cpp, src/gui/widgets/template_list_widget.cpp, src/templates/template.cpp, src/templates/template.h, src/templates/template_image.cpp, src/templates/template_position_dock_widget.cpp, src/templates/template_position_dock_widget.h, src/templates/template_tool_paint.cpp, src/util/transformation.cpp, test/transform_t.cpp
Enhances `fromQTransform` and `struct TemplateTransform` to fully reflect the
affine transformation that defines them.
This PR does not require #1277, though the need for each PR may arise in related circumstances.
In comparison to the approach taken with #1277, this PR is lighter weight. Rather than add to or replace TemplateTransform with an affine `QTransform`, a scalar `template_shear` member is added to the existing data structure.
[wintri-maps.zip](https://github.com/OpenOrienteering/mapper/files/3412647/wintri-maps.zip)
[7_tile_slope.zip](https://github.com/OpenOrienteering/mapper/files/3412645/7_tile_slope.zip)
The example maps illustrate a case in which the alignment of a template image can be improved. As with #1277 this case uses the Winkel III projection. For the current PR, …
=> TemplateTransform: allow any affine transformation

ci/azure-pipelines.yml, ci/openorienteering-mapper-ci.cmake, ci/setup-msys2.yml
The clazy job runs much longer now with clang-tidy and iwy.
The Linux debug/coverage job may run after the macOS job instead.
=> CI: Update job sequence

test/template_t.cpp
If the system locale is not UTF-8, QFile will run into trouble
when we try to access the UTF-8-named GeoTIFF test file.
=> TemplateTest: Tolerate non-UTF-8 systems

src/tools/draw_text_tool.cpp
For proper teardown of tools and MapEditorController, it is neccessary
to also update the tool's state itself.
Fixes GH-1418 (Crash when closing map during text editing).
=> DrawTextTool: Use base class tool state handling

doc/licensing/gentoo-licensing.cmake
Adding a gentoo-licensing.cmake to the source package would make it easier to build Mapper releases on my Gentoo-based desktop machine.
Gentoo Linux has support for all the third party dependencies except Polyclipping. I have my own "ebuild" files for Polyclipping and OpenOrienteering Mapper, which I may see about submitting for inclusion in the Gentoo distribution. These are fairly routine.
Gentoo's package database lists licenses, and for GDAL the list is  just "BSD Info-ZIP MIT". Text for each of these licenses is stored separately. It is meager in comparison to what Mapper shows for GDAL licensing on other platforms. I have set it up so that GDAL appears on Mapper's licensing page in a bare bones line just like the "easy" dependencies mentioned in `linux-distribution.cmake`. …
=> Support for Gentoo Linux (licensing)

src/core/symbols/line_symbol.cpp
Loop until the path part's last index. VirtualPath::size() does not
have the same meaning as STL containers' size().
Fixes GH-1448 (crash on OSM import).
=> LineSymbol: Fix coordinate shifting for holes

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_export.h, src/fileformats/ocd_types_v11.h, src/fileformats/ocd_types_v9.h
Per-symbol color information was implemented for the color bitmask
in OCD version 8, but not for the color counter and index list in
newer versions of the format.
Assumed to resolve GH-1452 (map not displayed in CONDES).
=> OcdFileExport: Update per-symbol color list

src/core/map.cpp, src/core/map.h, src/core/map_part.cpp, src/core/map_part.h, src/core/objects/boolean_tool.cpp, src/core/objects/object.cpp, src/core/objects/object_operations.h, src/core/symbols/symbol.cpp, src/core/symbols/symbol.h, src/fileformats/file_import_export.cpp, src/fileformats/xml_file_format.cpp, src/gui/map/map_editor.cpp, src/gui/symbols/point_symbol_editor_widget.cpp, src/gui/symbols/symbol_setting_dialog.cpp, src/tools/cut_tool.cpp, src/tools/cutout_tool.cpp, src/tools/edit_point_tool.cpp, src/undo/object_undo.cpp
This is part of code from PR#1251 which is making very slow progress. The three patches clean up minor troubles in `Map` API and `Symbol` id handling.
The remaining work for the symbol id undo is:
* Decoupling of symbol id from its position in symbol selector widget. I've hit several cul-de-sac's and I'm exploring a "sparse vector" implementation now.
* The actual symbol undo implementation, which does exist in https://github.com/lpechacek/mapper/tree/issue-1200-symbol-delete-undo and hit the roadblock of volatile symbol id assignment, needs stable symbol id for undo buffer serialization.
Please consider merging this preparatory cleanup work.
=> Minor refactoring of Map and Symbol object interfaces

src/gui/widgets/tag_select_widget.cpp, src/gui/widgets/tag_select_widget.h
Amends bd280de: Queue the button state update request after current
cell changes, so that addition and removal of rows may have completed.
Task: GH-1451
=> TagSelectWidget: Postpone button state update

src/core/map_printer.cpp, src/gui/print_widget.cpp
This PR has two commits. The first fixes #1209 "print area alignment error" by setting the QPrinter into full page mode in updatePaperDimensions. It also changes from using the obsolete QPrinter::getPageMargins to QPrinter::pageRect.
The second commit presents a suggestion, which arose while I was investigating #1209. Why was it biased toward retaining the top-left of the print area, while moving the bottom-right away from what the user selected earlier? This behavior is determined by PrintWidget::applyPrintAreaPolicy. I suggest preserving the center of the print area rather than the top left.
=> print area consistency

src/core/objects/object.cpp
This fixes the problem reported in #1467 with "import and remove" messing up the template position.
=> Object: Fix rotate() math.

src/gdal/gdal_manager.cpp
Closes GH-1476 (broken OSM support).
=> GdalManagerPrivate: Fix extensions removal

src/core/image_transparency_fixup.h, src/core/renderables/renderable.cpp
The function is deprecated.
Fixes build error on Arch Linux.
=> Modernize QImage::byteCount()

doc/manual/CMakeLists.txt, doc/manual/preprocess-markdown-pdflatex.cmake.in
Similar to Qt Help processing, use a custom command to preprocess
markdown for pdflatex only when needed.
=> doc/manual: Fix pdflatex rules

src/gui/map/map_editor.cpp
We must not immediately delete a TemplatePositionDockWidget when we
remove it from the list: When the removal is triggered from a close
event, there might be accesses following our event handling.
Fixes GH-1494 (crash on closing dock widget).
=> MapEditorController: Defer template position dock deletion

src/gui/widgets/symbol_render_widget.cpp, src/util/overriding_shortcut.cpp, src/util/overriding_shortcut.h
Efficiently track parent and top-level widget changes.
Respect disabled shortcut state.
=> OverridingShortcut: Revise event filtering

src/fileformats/xml_file_format.cpp, src/fileformats/xml_file_format_p.h
Modify declination when declination, grivation and convergence are
not consistent. Resolves GH-1235 (errors on editing declination).
=> XMLFileImporter: Validate declination/grivation

src/tools/draw_circle_tool.cpp, src/tools/draw_line_and_area_tool.cpp
For creating a circle, we need more than just the position of the
initial mouse press. That's why this tool leaves the preview object
empty after startDrawing(). However, the empty preview object must
not be added to the map on finishDrawing.
Fixes GH-1497 (crash after drawing with circle tool).
=> DrawCircleTool: Don't create empty objects

src/core/symbols/symbol.cpp
The icon is to represent the appearance on white paper. The GUI may
use a dark background color (e.g. macOS dark mode).
=> Symbol: White background for icons

src/gdal/ogr_template.cpp
When the map's projected CRS changes, the transformation of the
template's data is non-trivial. We might use modern (late-binding)
PROJ for precise transformation, but for now (until modern PROJ
is available and reliable everywhere) it is easier to just reload
the template.
=> OgrTemplate: Fix map projection changes

src/fileformats/ocd_file_export.cpp
The work is complete with regard to what was achieved for OCD 8 in
the legacy implementation. OCD export is still declared as lossy.
=> OcdFileExport: Remove WIP warning

src/templates/template_image.cpp
Changing whether a template is used georeferenced or not does not mean
that the template file itself should be rewritten. In fact, the old
behaviour is dangerous: Rewriting may cause loss of quality (JPEG) or
loss of georeferencing information (GeoTIFF -> TIFF).
=> Changing a template's georeferenced state may trigger lossy rewriting of the template file

src/gdal/gdal_image_reader.cpp, src/gdal/gdal_template.cpp, src/gui/select_crs_dialog.cpp, src/gui/select_crs_dialog.h, src/gui/widgets/template_list_widget.cpp, src/templates/template.cpp, src/templates/template.h, src/templates/template_image.cpp, src/templates/template_image.h, src/templates/template_image_open_dialog.cpp
Increase flexibility without further complicating the code. Most of all,
- allows overriding of CRS information when it differs from the map, or when (re-)enabling georeferencing for an existing template,
- mitigates GH-1515 (slightly misplaced templates.
=> Revise template georeferencing setup

src/fileformats/ocd_file_export.cpp
This used to be implemented in the legacy exporter but was still
missing in the new exporter. In orienteering maps, this affects
at least vineyards, orchards, forest runnable in one direction.
=> OcdFileExport: Export area object pattern rotation

3rd-party/cove/app/mainform.cpp, 3rd-party/cove/app/mainform.h, 3rd-party/cove/app/mainform.ui
It is very easy for a user to omit the thinning operation in line vectorization. The function then gives unsatisfactory results. This patchset makes CoVe emit a warning in case the user runs vectorization on B/W image which didn't see thinning. Attempt for proper integration with the undo/redo functionality resulted in the removal of the legacy code and adoption of `QUndoStack`. Although the rewrite is fairly straightforward, I'd appreciate a review. Thanks!
=> cove: Warn when vectorizing thick lines

src/core/renderables/renderable_implementation.cpp
Because the original implementation didn't sufficiently consider
180 deg turns when calculating extents, some objects might remain
invisible for certain viewports, and they were difficult to select
in the editor.
=> LineRenderable: Fix extent on 180 deg turns

src/core/map_coord.h
Const return types disallows some functional compositions.
=> MapCoord: Don't return const types

src/gdal/gdal_template.cpp
When QImageReader is used as a fallback after GdalImageReader failed,
and QImageReader fails, too, we shall combine the error strings:
The error message from GdalImageReader can be more specific.
Resolves GH-1550.
=> GdalTemplate: Don't lose GDAL error string

src/fileformats/ocd_file_import.cpp, src/fileformats/ocd_georef_fields.cpp, test/georef_ocd_mapping_t.cpp
We need to set the grivation even if it is the default value of zero.
This ensures that the declination is adjusted such that grivation,
declination and convergence are consistent.
Fixes GH-1552 (inconsistent import from OCD leading to later warning).
=> OcdFileImport: Always set grivation

src/fileformats/file_import_export.cpp, src/templates/template.cpp, src/templates/template_placeholder.cpp, src/templates/template_placeholder.h
This PR complements the changes introducing TemplatePlaceholder. In the end, it shall no longer be necessary to prefix supported filename extensions.
Fixes #1581.
=> Fix template type resolution

src/core/symbols/combined_symbol.cpp, src/gui/symbols/combined_symbol_settings.cpp
When the number of subsymbols decreases, we must block signal
emissions while resetting obsolete symbol edits.
Fixes GH-1600 (Crash when editing combined symbols).
=> CombinedSymbolSettings: Block signals on symbol reset

src/core/symbols/line_symbol.cpp, src/core/symbols/line_symbol.h
The path of a border line is determined by two factors: the main
offset, indicating the edge of the main line, and an explicit
additional offset.
Mapper used to rely on the main offset being non-zero in order to
distinguish left from right by the sign of the main offset.
With this change, Mapper now uses the totat offset to determine left
or right, thus allowing to use border lines with invisible main lines.
Fixes GH-1602 (wrong area border line path).
=> LineSymbol: Fix border line handling

src/core/georeferencing.cpp, src/core/georeferencing.h, test/georeferencing_t.cpp
Fixes the change of mapping between paper and ground when changing from a CRS to a local georeferencing and back, by retaining (fake) convergence and grid scale factor.
=> Georeferencing: Fix state switching

src/tools/edit_line_tool.cpp, src/tools/edit_line_tool.h, src/tools/edit_point_tool.cpp, src/tools/edit_point_tool.h, src/tools/edit_tool.cpp, src/tools/edit_tool.h
There is a heavy code duplication between edit point and edit line tools. The work done in the `EditTool` code aims at minimizing further code duplication.
=> EditPointTool,EditLineTool: Enlarge object frame (GH-980)

src/core/symbols/line_symbol.cpp
Amends 7c26d51.
Fixes GH-1608 (Crash with particular OCD file).
=> LineSymbol: Fix crash in createSinglePathRenderables

CMakeLists.txt
0.9.3 lives in the release branch only.
=> Set version to 0.9.4

test/georeferencing_t.cpp
Before PROJ 7.0.0, "WGS84" used to identify a geographic CRS (by
approximate match on "WGS 84"). Since 7.0.0, it identifies a datum
instead (by exact match).
Cf. https://github.com/OSGeo/PROJ/issues/2216.
=> GeoreferencingTest: Use "WGS 84" as CRS ID

src/fileformats/ocd_georef_fields.cpp, src/fileformats/xml_file_format.cpp, src/gdal/ogr_file_format.cpp, src/gdal/ogr_template.cpp, src/templates/template_image.cpp, src/templates/template_track.cpp, test/georef_ocd_mapping_t.cpp
When loading a template from an OCAD file, etc. and setting the projected reference point, hold on to the received combined scale factor rather than update it based on the auxiliary scale factor and grid scale factor.
This appears to fix #1620.
=> Georeferencing: Set reference point correctly when loading templates

src/gui/map/map_editor.cpp, src/gui/map/map_editor.h
While we use (some) dock widget location changes as triggers for
saving window state, other state changes happen without being
recorded immediately. Thus we need to rely on saveWindowState()
always saving the current state when called from detach() when
the map editor is in "normal" mode.
Resolves GH-1647 (unable to permanently restore missing toolbars).
=> MapEditorController: Fix window state saving

src/fileformats/xml_file_format.cpp
The warning shall not confuse users, but still give an indication
that manually checking the declination might be needed.
Task: GH-1235
=> XMLFileImporter: Adjust declination warning

src/gui/map/map_editor.cpp, src/gui/widgets/action_grid_bar.cpp, src/gui/widgets/mapper_proxystyle.cpp, src/gui/widgets/mapper_proxystyle.h, src/templates/paint_on_template_tool.cpp, src/templates/paint_on_template_tool.h
Replace the former proprietary `PaintOnTemplatePaletteWidget` by usage of the generic `ActionGridBar` (cf. GH-1673). This change facilitates development of scribbling features.
=> PaintOnTemplateTool: Use ActionGridBar for "palette"

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_import.cpp, src/templates/template_map.cpp, src/templates/template_map.h, src/templates/template_placeholder.cpp, src/templates/template_placeholder.h
A much simpler approach to handling the positioning of georeferenced OCD templates.
Replaces GH-1648.
=> Fix positioning of georeferenced OCD templates, simplified

src/fileformats/ocd_file_import.cpp, src/fileformats/ocd_file_import.h, test/file_format_t.cpp
... and add corresponding tests. 
There were no tests comparing symbols on the lossy OMAP to OCD transition. The tests added in this PR still cover only basic properties, but at least detect issue GH-1677.
=> OcdFileImport: Honor area hatch/structure north orientation

src/gui/main_window.cpp
The Back key is likely to be hidden and must be made visible by swiping from the bottom edge. Anyway, it is expected to close popups like the overflow action menu.
=> MainWindow: Close Android popups on Key_Back

src/gui/map/map_editor.cpp, src/templates/paint_on_template_feature.cpp, src/templates/paint_on_template_feature.h
... for selecting and templates.
(Split from GH-1706. Needs style udpdates for acceptable usability on Android.)
Template selection moved to scribble mode button (press-and-hold). Only templates in the current viewport, relative position indicated as icon.
=> PaintOnTemplateFeature: Use menu instead of dialog

src/gui/map/map_editor.cpp, src/gui/map/map_editor.h, src/main.cpp, src/sensors/CMakeLists.txt, src/sensors/fake_position_plugin.cpp, src/sensors/fake_position_plugin.h, src/sensors/fake_position_plugin.json, src/sensors/fake_position_source.cpp, src/sensors/fake_position_source.h, src/sensors/gps_display.cpp, src/sensors/gps_display.h, test/sensors_t.cpp
This is an (even more) simplifed version of a mode which makes the view follow the GNSS position.
- I prefer to call it "Follow-position mode" instead of "Tourist mode".
- It moves the viewport, but never changes zoom.
- I dropped the icon for now, although its quite nice indeed.
For easier desktop testing, I added a pending rewrite of the dummy position source.
=> Follow GNSS position

doc/manual/preprocess-markdown-html.cmake.in
Fixes "warning: multiple use of section label 'index'" with doxygen-1.8.20.
=> doc/manual: Don't duplicate the 'index' label

src/gui/main_window.cpp
This reverts commit 1fde405d1b914da06ba5f7ad999170d8edfb0c9a (and adds a comment), in order to make template loading notifications more reliable on slower Android devices.
=> Revert "MainWindow: Shorten event processing on message"

3rd-party/cove/tests/CMakeLists.txt, 3rd-party/cove/tests/PolygonTest.cpp, 3rd-party/cove/tests/PolygonTest.h, 3rd-party/cove/tests/test_config.h.in, doc/manual/CMakeLists.txt, test/autosave_t.cpp, test/file_format_t.cpp, test/symbol_set_t.cpp, test/template_t.cpp, test/track_t.cpp
The manual issue affects all binary packages which include the manual (Qt Help format).
The QFINDTESTDATA() issue doesn't affect binary packages, but test executables. In this sense, it is more or less a false positive.
=> Fix reproducibility issues

src/templates/template.cpp, src/templates/template_map.cpp
When configuring a template for the first time, we don't need to,
and sometimes are unable to properly, set the template area dirty
immediately after loading: the template area might be adjusted by
the postLoadSetup(), or by setupAndLoad() for center_in_view.
This is reflected by leaving the Configuring state unchanged after
successful loadTemplateFileImpl(), and by moving the resposibility
for the state change to the end of setupAndLoad().
=> Template: Delay setTemplateAreaDirty on setup

src/fileformats/file_import_export.cpp
Closes GH-1766 (Empty template warnings when loading maps).
=> Importer: Fix template warnings

3rd-party/cove/libvectorizer/Concurrency.h, src/core/objects/object.h, src/gdal/ogr_file_format.cpp
A tiny change which will make build with Clang 11 possible in Fedora 33 and openSUSE Tumbleweed.
=> treewide: Fix warnings reported by Clang 11

src/core/georeferencing.cpp, src/core/georeferencing.h, src/fileformats/file_import_export.cpp, src/fileformats/xml_file_format.cpp, src/gdal/ogr_file_format.cpp, src/gdal/ogr_template.cpp, src/gui/georeferencing_dialog.cpp, src/gui/map/map_dialog_scale.cpp, src/gui/map/map_editor.cpp, src/gui/map/rotate_map_dialog.cpp, src/gui/map/stretch_map_dialog.cpp, src/gui/select_crs_dialog.cpp, src/gui/widgets/template_list_widget.cpp, src/templates/template_image.cpp, src/templates/template_map.cpp, src/templates/template_track.cpp, test/file_format_t.cpp, test/georeferencing_t.cpp, test/georeferencing_t.h, test/template_t.cpp
Preparatory work for template class changes and for more georeferencing changes:
Strictly use an enum value to distinguish local, geospatial, and
invalid geospatial states of georeferencing.
This is complemented by making setState() a private member.
There was no simple test if a georeferencing was geospatial AND valid.
Mapper code had to combine isValid() && !isLocal() to test for this
state. By consistently using the state enum, and adding a state for
invalid geospatial references, code is logically simpler and more
expressive.
Note that the existing state checks were not translated literally,
but adjustments were made where the original seemed to not match
the required context.
=> Georeferencing: Revise state API

src/gdal/ogr_file_format_p.h
This commit fixes a bug found by Valgrind. This is a minimal fix to the issue at hand, which raises a question of to what degree we want to adhere to the ES.20 (Always initialize an object) guideline. `OgrFileImport` class contains, in its `private:` section, an even mix of constructor-initialized members and member-initialized ones. For instance, the `default_*_symbol` members are initialized in the single class constructor, and the many POD members (`empty_geometries`, `no_transformation`, ...) have default member initializers. `OGRSpatialReferenceH`, which is a pointer in disguise, fell through the cracks.
Do we want to routinely provide in-class default member initializers for anything that might potentially be a POD, or do we stick to the current habits and rely on specialized tools …
=> OgrFileImport: Initialize data_srs on construction

src/fileformats/file_format.cpp, src/fileformats/file_format.h, src/fileformats/file_import_export.cpp, src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_import.cpp, src/fileformats/xml_file_format.cpp, src/gdal/ogr_file_format.cpp
Replaces Q_ASSERT in export/import by a macro which throws proper exceptions instead of letting the app run into crashes in release builds.
Fixes a duplicate error message labeling with "Cannot save file ...".
=> Improve error reporting on saving/loading

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_export.h, src/fileformats/ocd_file_import.cpp
Avoid some pointless imports of OCD line symbols as combined symbols.
Fix export of area-with-border even for (some) borders which are combined symbols.
Turn Q_UNREACHABLE into proper exceptions in order to avoid aborting or UB.
=> OCD support improvements

test/template_t.cpp
For simplicity, disable some tests on Qt < 5.9 or big endian machines.
=> TemplateTest: Fix special builds

src/core/symbols/area_symbol.cpp
The name property is transient, only used by the symbol editor UI.
It is not exported or imported. For proper merging of imported
symbols, fill pattern comparison must ignore the name.
Fixes GH-1828 (duplicate symbol after edit, copy, paste).
=> AreaSymbol::FillPattern: Don't compare the name

src/templates/paint_on_template_feature.cpp
Indicate that template configuration is finished before loading the
template file, so that that function takes care of setting the state
to Loaded on success.
Complements aee1057f.
Fixes GH-1830 (Cannot add scribble template).
=> PaintOnTemplateFeature: Fix setupTemplate()

src/core/symbols/combined_symbol.cpp
Some patterns may be null. :facepalm: 
Amends 095bb634.
Resolves GH-1835 (Crash with certain objects).
=> CombinedSymbol: Fix hasRotatableFillPattern()

src/templates/template_map.cpp, src/templates/template_map.h
- Center added templates also when the map has no geospatial reference.
Faciltates using the Course Design symbol set on legacy maps.
- Enable toggling of georeferenced state.
Allows to reset the template position.
- Trigger the map georeferencing dialog when adding a TemplateMap to a map has no valid geospatial reference.
Again, this is useful for the Course Design symbol set, but also for fresh starts in regular mapping.
=> Improve georef handling for template maps

src/core/objects/boolean_tool.cpp
PathObject::changePathBounds() expects non-empty segment lengths.
Fixes clipping during OGR data loading.
=> BooleanTool: Fix usage of changePathBounds()

ci/setup-common.yml
Azure Pipelines started setting ANDROID_NDK_ROOT which breaks the
initialization of 'sdk_host' in Superbuild's Android toolchain setup.
=> CI: Workaround superbuild Android sdk_host quirk

src/gui/georeferencing_dialog.cpp
Map Georeferencing now shows a marker at the reference point in OpenStreetMap lookup of the position.
In addition the lookup operates with an improved precision.
=> OpenStreetMap lookup of reference point to show marker

code-check-wrapper.sh, src/CMakeLists.txt, src/gui/settings_dialog.cpp, src/gui/util_gui.cpp, src/gui/util_gui.h, src/gui/widgets/color_list_widget.cpp, src/gui/widgets/color_list_widget.h, src/gui/widgets/color_wheel_widget.cpp, src/gui/widgets/color_wheel_widget.h, src/gui/widgets/paint_on_template_settings_page.cpp, src/gui/widgets/paint_on_template_settings_page.h, src/gui/widgets/tag_select_widget.cpp, src/gui/widgets/tag_select_widget.h, src/gui/widgets/tags_widget.cpp, src/gui/widgets/tags_widget.h, src/gui/widgets/template_list_widget.cpp, src/settings.cpp, src/settings.h, src/templates/paint_on_template_tool.cpp
Let's give a shot to this implementation of the scribble color settings dialog. It may feel rough but at the same time it might be "just right". Comments are welcome especially in the following areas:
* Are the scribble colors device-dependent or map-dependent? I.e. should the setting be stored on the device on in the map file?
* Is the user interface usable on mobile devices?
=> PaintOnTemplateTool: Add color setup page to Settings

src/core/map.cpp
The scheduled template loading event is bound to the lifetime of the
template object, but the lambda captures a reference to the unique_ptr
owning the template. The lifetime of the unique_ptr can end before the
lifetime of the pointed-to object when ownership is transferred to
another unique_ptr. Here, this is triggered when the the template
container reallocates memory due to insertion.
We can safely capture a raw pointer to the template instead.
Fixes GH-1893 (crash on early location display toggle).
=> Map: Fix unsafe reference to unique_ptr

src/gui/widgets/tags_widget.cpp
... when removing the first row. Fixes a quirk with the value of the
new first row being invisible or lost.
=> TagsWidget: Rely on QTableWidget::removeRow()

src/fileformats/ocd_georef_fields.cpp, test/georef_ocd_mapping_t.cpp
From the beginning, the intent was to translate zone is'd 8002 through
8005 directly into Mapper's native MapperCrs::GaussKrueger zone and look
up the other ones in the generic zone-EPSG code table.
Closes GH-1912
=> OCD: Fix handling of OcdGrid::Germany (8xxx) zones

doc/manual/install-html.cmake.in
Ensure an absolute path, but don't blindly prepend
CMAKE_INSTALL_PREFIX.
Fixes GH-1906 (manual pages installed in wrong place).
=> doc/manual: Fix html pages installation

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_import.cpp
Mapper currently saves the View settings of Hatch areas and Baseline view to .omap.
With this change Mapper exports and imports the View settings to .ocd (Baseline view is denoted as Keyline mode and is present for OCAD 11 and newer, however not for all editions and not in the OCAD viewer).
=> OCDImportExport: import and export of Hatch areas and Baseline view state

src/gui/map/map_editor.cpp
Adds 'X' as a shortcut for 'Cut away from area', as suggested in #2011.
=> Shortcuts: Add 'X' as a shortcut for 'Cut away from area'

src/core/georeferencing.cpp, test/template_t.cpp
This is a possible alternative solution to #2008, rather than revising the expected template test failures as in #2009.
By setting up the PROJ transformation with an added option to permit _any_ authority, the tracks that relate to NAD83-based maps are placed more accurately than when processed via GDAL. With this change, those test tracks are positioned the same as they are by the Mapper executables in the 0.9.5 release.
=> Preserve GPX track accuracy by accepting any authority

src/fileformats/ocd_file_export.cpp, test/data/undefined-objects.omap, test/file_format_t.cpp
A real fix to the .ocd export issue reported by users. Feel free to edit/reimplement it to your liking.
=> Handle undefined symbols in .ocd export

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_types_v8.h
When exporting more than 32 custom tabulator positions the num_tabs
field is now limited to the 32 tabs that are actually only exported and
a warning messages is issued (issue was detected by lpechacek).
In addition the export now converts the tabulator position to a 32 bit
value since the convertSize function that was used before converted it
to a 16 bit value instead (which was indeed only relevant for tab
values larger than 327,67mm).
=> OcdFileExport: Fix export of custom tabulator positions

src/fileformats/ocd_file_export.cpp
If the size of the map notes exceeded 32768 the map notes were truncated when saving as OCAD 8.
However, instead of truncating to 32767 (the terminating 0 will be appended) it was truncated to 23767.
When testing the fix with OCAD12 it turned out that it was necessary to truncate to 32766, otherwise OCAD12 would not open the map.
=> OcdFileExport: Fix map notes export to .ocd version 8

src/fileformats/ocd_file_import.cpp, src/fileformats/ocd_file_import.h
The 'GridFlags' field consists of 3 bits: 1=Grid On, 2=Numbering On, 4=Numbered from the bottom
The symbol import previously only considered Grid On and mapped 'Numbered from the bottom' to Bit 1 instead.
When importing Rectangle objects the 'Numbered from the bottom' property was applied just the other way around.
=> OcdFileImport: Fix import of Rectangle symbols and objects

src/core/symbols/text_symbol.cpp
For comparing 'custom_tabs' and 'text->custom_tabs' which are both of type std::vector<int>
it is more efficient to use == which does exactly was implemented before manually:
check the sizes and if both vectors are of equal length compare the content.
=> TextSymbol: Optimize comparision of custom tabs

src/fileformats/ocd_parameter_stream_reader.cpp, src/fileformats/ocd_parameter_stream_reader.h, test/ocd_parameter_stream_reader_t.cpp
@dl3sdo A few more changes which I couldn't finish before this afternoon. Would have been much harder without the unit test. 
Apart from documentation, this change ensures that `param_string.indexOf(QLatin1Char('\t') ...)` is called only once per tab character. All complexity is in `readNext()`.
=> OcdParameterStreamReader: Documentation, more state

src/fileformats/ocd_file_export.cpp, src/fileformats/ocd_file_export.h
A significant part of text symbol export for OCD is preparatory stuff,
independent of actual OCD format. This commit adds a separate member
function, helping to minimize the code size of the template function.
=> OcdFileExport: Factor out prepareTextSymbolExport()

src/gdal/gdal_settings_page.cpp
When a duplicated 'Parameter' is entered the behaviour depends whether
the row is the last row or not.
If it's not the last row, then the complete row is removed, i.e. also
the 'Value' content is deleted.
If it's the last row then just the cell contents shall be deleted.
However, due to a copy-and-paste error only the 'Parameter' cell
content was deleted (twice).
=> GdalSettingsPage: Delete 'Value' cell

src/core/objects/object_query.cpp, test/object_query_t.cpp
There are two bugs in object_query.cpp:
- for special object queries an out_of_range access occurs which leads to a crash in the Debug version.
- the fromEscaped() functions fails for sequences of escaped characters (to verify the correct behaviour a test was added to ObjectQueryTest).
The last change is the removal of an unnecessary if condition.
=> ObjectQueryParser: Object query fixes

doc/licensing/arch-licensing.cmake
This change enables cmake to find the GDAL's LICENSE.TXT.
=> Licensing: Find GDAL license on Arch Linux

src/gui/map/map_editor.cpp
The edit mode is selected by default on editor startup. However, in the touch UI, object editing is rarely the first action to be done after opening a map. The user typically pans the map view to the area of interest first and then starts editing.
This code change makes the touch UI start in the view pan mode. The desktop action remains to be editing as the desktop users use mouse middle button for editing.
Discussed in GH-982.
=> MapEditorController: Select pan tool on touch UI startup

3rd-party/cove/libvectorizer/Polygons.cpp, 3rd-party/cove/libvectorizer/Polygons.h
Address a tiny warning from a new GCC.
=> CoVe: Address GCC warning about std::binary_function

src/core/objects/symbol_rule_set.h
Fixing several typos in symbol_rule_set.h
=> SymbolRuleSet: Fix typos

src/core/image_transparency_fixup.h, test/qpainter_t.cpp
https://bugreports.qt.io/browse/QTBUG-100327 was fixed in 5.15.9, so now we have a good result from the beginning and don't need ImageTransparencyFixup.
This fixes a test failure which can be seen in [this log](https://launchpadlibrarian.net/666512825/buildlog_ubuntu-mantic-amd64.openorienteering-mapper_0.9.5-3build8_BUILDING.txt.gz).
=> Make QPainterTest pass with Qt 5.15.9

src/gui/color_dialog.cpp, src/gui/color_dialog.h
Currently it's somewhat difficult to identify symbols that use a certain color. This change set adds a list showing the color usage in symbols ~~and the possibility to trigger symbol editing dialog from the color dialog~~.
Use case - color table clean up after map/symbol set import.
[Screencast from 2023-09-10 19-52-49.webm](https://github.com/OpenOrienteering/mapper/assets/5584406/ddcb82c0-df19-4da7-8e94-f13a993e3b51)
=> Color edit dialog - show symbol usage

src/core/objects/object_query.cpp, src/core/objects/object_query.h, src/gui/map/map_find_feature.cpp
The map object is needed for SYMBOL queries.
Fixes GH-2183.
=> MapFindFeature: Pass map to query parser

src/fileformats/ocd_file_import.cpp
Text symbols in .ocd files can contain an additional point symbol that is currently silently ignored when importing such files. This change issues a detailed warning when ignoring an additional point symbol.
=> OcdFileImport: Warn about ignored point symbol in text symbol

test/track_t.cpp
Prevents EOL mismatch on Windows.
=> TrackTest: Load GPX files as text

src/core/map_color.cpp, src/core/map_color.h
Avoid warning by removing unused 'this' from capture clause.
Simplify implementation by removing unnecessary checks and using bitmask values in the typical way.
=> MapColor: Fix warning and simplify implementation

src/util/xml_stream_util.cpp
When opening an .omap file, the error messages being shown if the actual number of object coordinates doesn't match the number inside the file didn't contain both numbers since these were not passed by arg().
=> XmlElementReader: Fix file format error messages

symbol sets/OSM-ISOM 2017-2.crt, symbol sets/OSM-ISSkiOM 2019.crt, symbol sets/OSM-ISSprOM 2019.crt
Adding more OSM tags which can be translated into orienteering map symbols.
Namely:
- natural=peak
- leisure=picnic_table
- highway=primary_link
- highway=secondary_link
- highway=tertiary_link
- highway=steps
- tourism=information (restricted to guidepost, map or board)
- historic=memorial
- historic=wayside_cross
All of these I considered useful when I was preparing a base for my latest map.
=> Enhance CRT transformations from OSM to ISOM/ISSprOM/ISSkiOM symbol sets

src/gui/widgets/tags_widget.cpp
The 'help' button was not connected to actually show the related help content.
When setting the margins around the 'help' button, the top margin parameter was accidentally set to QStyle::PM_LayoutLeftMargin instead. Now using 0 as in ColorListWidget.
=> TagsWidget: Fix tag editor setup

src/core/virtual_path.cpp, test/path_object_t.cpp, test/path_object_t.h
The crash fixed in GH-2224/GH-2144 had an OCD import aspect (data source) and an map editor aspect (data usage). This PR adresses the second aspect. While it was easy to locate the crash and its trigger, a confusing fact was that the path part data in the map editor wasn't the same as the data observed while debugging the OCD import. It furned out that the initial calculation of map parts in `PathObject::recalculateParts()` (expected data) was overwritten by `PathObject::updatePathCoords()` (actual data).
This PR aligns map part calulation in the second function with the first function, and a adds a basic test. This fixes the crash. 
There is a certain risk that this creates new problems. But the generated data is fairly reasonable now.
=> Fix "empty hole" quirks

ci/shell.sh
Ported from OpenOrienteering/superbuild, needed for CI update.
=> CI: Don't use MSYS2 stdbuf

src/gui/widgets/color_list_widget.cpp
The individual setting 'QHeaderView::Stretch' of the 'Name' column's resize mode was erroneously overwritten by the setting which was intended for the 'Spot color' column.
Since 'QHeaderView::Stretch' results in undesired behaviour the default setting 'QHeaderView::Interactive' is kept.
=> ColorListWidget: Fix table column resize mode

src/core/map.cpp, src/core/map.h, src/core/map_color.cpp, src/core/map_color.h, src/gui/map/map_editor.cpp, src/gui/widgets/color_list_widget.cpp, src/gui/widgets/color_list_widget.h
Modification of GH-2209, GH-2235
- Don't use more than `overprinting_simulation_act` in `MapEditorController::spotColorPresenceChanged`.
- Add and use iteration functions for colors and symbols (long-standing wishlist item :innocent:)
- Show the color name in the spot color removal message. Feels more comfortable when confirming.
=> Warn on spot color deletion

src/gui/georeferencing_dialog.cpp
Since the link to 'World of O' to lookup maps is not working for quite a long time and as this service is apparently no longer provided, remove the link by commenting it out in the code.
=> GeoreferencingDialog: Remove link to WorldofO

src/gui/widgets/measure_widget.cpp, src/gui/widgets/measure_widget.h
This change enhances visibility of the small object warning in the measure tool. The use case is to shrink the measure tool window to a minimum size so that only the top line is visible and keep it in the view field during drawing. New sub-size object will trigger the colored warning icon, giving the user opportunity to fix the legibility issue on the go.
Idea contributed by @ollesmaps.
=> MeasureWidget: Show warning icon for small objects

ci/azure-pipelines.yml
Increasing job level timeout to task level timeout (now 90min due to #2253).
Referring to [Task control options' Note](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options)
=> CI: Increase job timeout

src/gui/map/map_editor.cpp
The 'Select all objects with selected symbols' menu item below the 'Edit' menu was enabled even if no symbols were selected. The same menu item in the popup symbol menu of the symbol pane however was disabled if no symbols were selected.
Move the enabling or disabling of the menu item to a function which is called by a change of the selected symbols and disable the menu item if no symbols are selected.
=> MapEditorController: Disable menu item if no symbols are selected

code-check-wrapper.sh, src/CMakeLists.txt, src/core/symbols/html_symbol_report.cpp, src/core/symbols/html_symbol_report.h, src/gui/map/map_editor.cpp, src/gui/map/map_editor.h, src/gui/symbols/symbol_report_feature.cpp, src/gui/symbols/symbol_report_feature.h
This feature is to help with validation symbol sets with regard to specifications and existing symbol sets.
UI: Symbols > Create symbol set report
The current implementation create a single-file HTML report which directly embeds all images.
=> SymbolReportFeature: Generate reports for symbol sets

src/fileformats/file_import_export.h, src/fileformats/iof_course_export.h, src/fileformats/kml_course_export.h, src/fileformats/ocd_file_export.h, src/fileformats/ocd_file_format.h, src/fileformats/ocd_file_import.h, src/fileformats/ocd_icon.h
Fix some include guards in fileformats folder.
I noticed that the comment after the final #endif is mostly missing so I'm not going to further fix it.
=> Fix include guards

ci/publish-coverage.yml
Although the current V1 version of the publish code coverage results task is still available it's recommended to stop using the V1 version and migrate to V2 version.
=> CI: Migrate from PCCR@V1 to ReportGenerator

test/file_format_t.cpp, test/file_format_t.h
Extended version of the proposed test, https://github.com/OpenOrienteering/mapper/pull/2224#issuecomment-2258301038
=> Test OcdFileImport::fillPathCoords

src/fileformats/ocd_file_export.cpp
Although OCD v8 is an old one, Mapper is the only software left to support writing these files. In my opinion, bugs are worth fixing in this part of the code.
Closes GH-291.
=> OcdFileExport: Fix OCD v8 object size calculation

src/gui/symbols/symbol_replacement_dialog.cpp
Since saving a CRT file may overwrite an existing CRT file it's better to use QSaveFile instead of QFile.
=> SymbolReplacementDialog: Use QSaveFile class

src/gui/map/map_editor.cpp
The pointer variables `gps_display`, `gps_track_recorder`, `compass_display` and `gps_marker_display` are all zero-initialized in the constructor. In `MapEditorController::detach()` all of their associated objects are deleted and the variables are set to nullptr. In the destructor however the `gps_marker_display` object was not deleted whereas the other three objects were.
=> MapEditorController: Delete object in destructor

src/core/symbols/html_symbol_report.cpp, src/gui/map/map_editor.cpp, src/gui/widgets/color_list_widget.cpp, test/file_format_t.cpp
Use function Symbol::getNumberAndPlainTextName() which was introduced by GH-2125 instead of concatenating symbol number and symbol name.
=> Use function Symbol::getNumberAndPlainTextName()

src/gui/symbols/line_symbol_settings.cpp
The 'mid symbol distance' field and label were not correctly disabled and enabled.
Enabling them by increasing 'Mid symbols per spot' was not possible unless reentering the symbols setting dialog. If they were enabled, removing the mid symbol would not disable them.
Adding both to `mid_symbol_widget_list` solves the issue.
Alternatively it would have been possible to replace in `mid_symbol_distance_edit->setEnabled(mid_symbol_distance_edit->isEnabled() &&` ...
by
`mid_symbol_distance_edit->setEnabled(!symbol->mid_symbol->isEmpty() &&` ...
=> LineSymbolSettings: Fix enabling/disabling in line symbol editor

src/core/symbols/combined_symbol.cpp, src/core/symbols/combined_symbol.h, src/core/symbols/line_symbol.cpp, src/core/symbols/line_symbol.h, src/core/symbols/symbol.cpp, src/core/symbols/symbol.h, src/tools/draw_path_tool.cpp, src/tools/edit_point_tool.cpp
When drawing line objects for symbols with dash symbols, no dash points were set automatically if the symbol was a combined symbol.
When editing line objects for symbols with dash symbols, additional points were not added as dash points if the symbol was a combined symbol.
These deviations were known and marked as TODO.
This commit treats line symbols with dash symbols and combined symbols containing line symbols with dash symbols equally.
=> Consider dash symbols in combined symbols

src/core/renderables/renderable_implementation.cpp
=> Fix rendering of cross-hatched areas

code-check-wrapper.sh, src/core/symbols/area_symbol.h, src/core/symbols/combined_symbol.cpp, src/core/symbols/combined_symbol.h, src/core/symbols/line_symbol.h, src/core/symbols/symbol.cpp, src/core/symbols/symbol.h, src/gui/widgets/measure_widget.cpp, test/symbol_t.cpp
Combined symbols may contain areas with a minimum size, either in area symbols or private sub-symbols.
Combined symbols may contain lines with a minimum size, either in line symbols or private sub-symbols.
This is an alternative implementation of GH-2084.
Closes GH-2083.
=> Consider minimum area and length in combined symbols

src/gui/symbols/text_symbol_settings.cpp
When entering the text symbol settings dialog the 'OK' and 'Reset' buttons where initially enabled.
Don't misuse the `framingCheckClicked()` function to enable/disable the `framing_widget` tab in `updateGeneralContents()` as `framingCheckClicked()` will signal modified properties.
=> TextSymbolSettings: Fix initial state of standard buttons

code-check-wrapper.sh, src/gui/symbols/point_symbol_editor_widget.cpp, src/gui/symbols/point_symbol_editor_widget.h
When adding a path point by clicking on the '+' button either a default point is appended to the path or an existing path point is duplicated.
However, when duplicating an existing point, also the CurveStart property was duplicated which lead to two successive path points with the CurveStart property being set although the next two path points following a CurveStart path point define the course of the curve and thus can't be a CurveStart path point itself.
Closes #2090 (Symbol Editor: Cannot remove coordinate pairs).
Additional fixes:
- When adding a path point by the '+' button the symbol was not updated. Since the point is normally duplicated this had no visual impact. However, if no row is selected then a default point at (0,0) is created which was not shown in this case.
- When the …
=> PointSymbolEditorWidget: Don't duplicate CurveStart property

src/core/map_view.cpp, src/core/map_view.h, src/fileformats/xml_file_format.cpp, src/fileformats/xml_file_format.h, src/gui/print_widget.cpp
Although the map visibility is stored in the map file the map became always visible after loading.
Amends commit 701902d (MapView/MapWidget: Review, fast pinching support).
Closes GH-2316 (Map is always visible after loading).
=> MapView: Restore map visibility after loading

src/core/map.cpp
Deleting a selection of objects lead to a corrupted undo step which could lead to a failure when undoing the undo step before. The reason was that the selected objects were added in a loop to the undo step including their object index. After adding an object it was removed which caused the indexes of the remaining (and sometimes to be removed as well) objects to be renumbered.
Use the AddObjectsUndoStep::removeContainedObjects() function to remove the objects once they all have been added.
Closes GH-2320 (Deleting objects corrupts undo step).
=> Map: Fix deleting object selection

doc/licensing/CMakeLists.txt, doc/licensing/ubuntu-licensing.cmake
The `$ID_LIKE` variable in `/etc/os-release` file may list space separated names that the current distribution is similar to. For example in some random distribution that derives from Ubuntu the values could be:
ID="random-distro"
ID_LIKE="ubuntu debian"
When trying to guess the current system, use all those values in order and use the first one that is known.
Here's documentation for the `ID_LIKE` variable: https://www.freedesktop.org/software/systemd/man/latest/os-release.html#ID_LIKE=
=> Licensing: Consider derivative distributions

3rd-party/cove/libvectorizer/Concurrency.cpp, 3rd-party/cove/libvectorizer/Concurrency.h
Move construction of Progress: No problem, sharing from const ref.  
Copy construction of Job: No problem.  
Assignment of Progress or Job: Not possible.  
Fixes GH-2334.
=> Progress,Job: Fix construction and assignment

src/gui/widgets/tag_select_widget.cpp
The 'Find objects' dialog contains a table which is shown in the 'Query editor' view.
The 'Relation' and 'Comparision' columns were set up with a fixed width based on the width of the translated labels 'Relation' and 'Comparision'. The result looks good for English but not for other languages, e.g., German or Czech.
Set up both columns to automatically resize based on its contents.
=> TagSelectWidget: Change column width

src/gui/georeferencing_dialog.cpp, src/gui/georeferencing_dialog.h
When switching between local and geospatial CRS links to OpenStreetMap | World of O Maps were shown even if they were not clickable (for local CRS).
This could also happen for a local CRS when using the Pick on Map and then pressing Reset.
Besides that there was an orphan 'Show reference point in:' label for local CRS.
The commit now uses setVisbible() for both, the label and the links, instead of just using setEnabled() on the links.
When setting up the dialog there was a doubled call edit_layout->addRow(show_refpoint_label, link_label); which lead to adding an empty row. This has been fixed by replacing it by adding a SpacerItem instead.
The last change corrects the link to OpenStreetMap.
mlat and mlon coordinates are now created by 'f', 6 instead of 'g', 10 which is the appropriate …
=> GeoreferencingDialog: Hide 'Show reference point in' for local CRS

src/fileformats/xml_file_format.cpp, src/fileformats/xml_file_format.h, test/file_format_t.cpp
When importing a spot color, setting the screen angle and screen frequency properties was ignored since the color was not yet defined as a spot color.
Close GH-2348 (Impossible to load screen frequency).
=> XMLFileImporter: Fix screen attributes import

src/gui/widgets/tags_widget.cpp
There is not (yet) a specific help file just for the object tag editor, but the editor
is covered by 'object_tags.html'.
=> TagsWidget: Correct link to help file

src/gui/widgets/tags_widget.cpp
If multiple objects were selected the tag editor would just operate on the so-called 'first selected object'.
If a group of objects is selected the user does not know which of them is the first selected object.
=> TagsWidget: Disable editing if multiple objects are selected

ci/azure-pipelines.yml
Fixes GH-2367.
CI is already modified to use the artifacts from the update superbuild.
=> CI: Roll windows images to 2022

src/gui/symbols/area_symbol_settings.cpp, src/gui/symbols/line_symbol_settings.cpp, src/gui/symbols/point_symbol_editor_widget.cpp, src/gui/symbols/point_symbol_editor_widget.h, src/gui/symbols/point_symbol_settings.cpp
Complements #2378. 
The point symbol editor widget is used for pattern fills in area symbols. It featured the "Always oriented to north (not rotatable)" checkbox, but this checkbox didn't have an effect in that use case. This PR hides the checkbox. This should reduce confusion, in particular with the same checkbox added to the area symbol itself in #2378.
NB: The checkbox has an effect for line symbol decorators. I wouldn't say it is intented, but I don't want to change this now.
=> PointSymbolEditorWidget: Hide oriented-to-north for area symbol patterns

src/core/map_coord.h
Get rid of warnings about deprecated language pattern.
=> MapCoordF: Declare copy assignment operator

src/templates/template_adjust.cpp
Disable the corresponding tool if no pass points are available to be moved or deleted and in case all pass points are removed.
=> TemplateAdjustWidget: Disable tool
